### ISSUE TITLE
Permission-editing: no issue!

### ISSUE THREAD

**Issue by die2** [Fuechschen/dubbot#13]
If i wanted to edit the permission table what file would need to be edited i cant seem to find!
plz! all i need is a list of files needed to be edited!

**Comment by Fuechschen** [comment]
If you mean, you want to have other permisions for cammnds, you will have to edit the bot itself since it's currently not possible to assign permissions to commands in a configuration.

To run the bot, only config.js has to be edited, but you can also customize your messages with language.js in /files.

**Comment by die2** [comment]
ty sir

**Comment by die2** [comment]
https://stg.plug.dj is back! ^_^

**Comment by Fuechschen** [comment]
preparement has already started: https://github.com/Fuechschen/plugbot

feel free to ask if you need something
